repos:
  # - repo: https://github.com/cmhughes/latexindent.pl.git
  #     rev: V3.24.5
  #     hooks:
  #       - id: latexindent

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # - repo: local
  #   hooks:
  #     - id: check-latex-errors
  #       name: Check LaTeX errors
  #       entry: bash -c "pdflatex -halt-on-error -interaction=nonstopmode main.tex"
  #       language: system
  #       files: \.tex$

  - repo: local
    hooks:
      - id: replace-bad-chars
        name: bad characters in .tex/.bib
        entry: .githooks/replace-bad-chars.sh
        language: system
        files: \.(tex|bib)$
